services:
    web:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ./docker/dev/site.conf:/etc/nginx/conf.d/default.conf
            - /private/var/log/nginx:/var/log/nginx
        networks:
            - prod-network
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure

    php:
        image: ${ImageName}
        networks:
            - prod-network
        deploy:
            mode: replicated
            replicas: 5
            restart_policy:
                condition: on-failure

networks:
  prod-network:
    driver: overlay
